#### Université de Bordeaux,  Master Mention Informatique,  2021-2022

# Analyse, classification et indexation des données: feuille 3
### Descente de gradient

##### Avant de commencer :
La méthode de la descente de gradient permet de trouver un minimum local d’une fonction de ${\mathbb R}^n$ dans ${\mathbb R}$ . L’objectif de ce TD est de comprendre cette méthode pour pouvoir l’utiliser par la suite dans différentes applications où on cherche à minimiser un critère.


Comme précédemment nous utilisons entre autres <code>numpy</code> pour manipuler vecteurs et matrices.

In [1]:
import numpy as np

### Exercice 1. Polynôme :  calcul et dérivée

1. Ecrivez une fonction python <code>valeurPolynome (coeff, x)</code> qui calcule la valeur du polynôme défini par le vecteur de coefficients <code>coeff</code> pour la valeur <code>x</code>. Les coefficients sont rangés dans l'ordre des puissances croissantes. Par exemple le vecteur $[1, 2, 3]$ définit le polynôme $3x^2+2x+1$. <br>Utilisez pour cela la classe <code>Polynomial</code> du module <code>numpy.polynomial</code>.

In [2]:
def valeurPolynome(coeff, x):
    coeff = np.polynomial.Polynomial(coeff)
    return coeff(x)


2. Testez cette fonction pour différentes valeurs de <code>x</code> et pour un polynôme dont vous choisirez les coefficients. Remarquez que le paramètre <code>x</code> peut lui même être un vecteur ou une matrice.

In [3]:
print(valeurPolynome([1,3,6],2))
M1 = np.array([[10, 20, 30], [40, 50, 60], [70, 80, 90]])
M1.shape
print(valeurPolynome([1,3,6],M1))

31.0
[[  631.  2461.  5491.]
 [ 9721. 15151. 21781.]
 [29611. 38641. 48871.]]


3. La dérivée d’un polynôme est elle même un polynôme. Toujours en utilisant la classe <code>Polynomial</code>, écrivez une fonction python <code>derivPoly(coeff)</code> qui retourne le tableau de coefficients représentant la dérivée du polynôme défini par <code>coeff</code>. Testez.

In [4]:
def derivPoly(coeff):
    var = np.polynomial.Polynomial(coeff)
    x = var.deriv()
    return x.coef

print(derivPoly([1,2,3]))

#print(derivPoly))

# var = np.polynomial.Polynomial([1,2,3])
# x = var.deriv()
# print(x.coef)

[2. 6.]


### Exercice 2. Descente de gradient pour trouver le minimum d’une parabole

1. Exécutez le script python suivant : 

In [5]:
%matplotlib 
import matplotlib.pyplot as plt

def parabole(x):
    return x * x

x = np.linspace(-300,300,600)
y = [parabole(i) for i in x]

epsilon = 0.01 #regle la convergeance
nu = 0.1 #pas d'apprentissage

plt.plot(x,y,'g')

x0=250 #on part de la droite
xcurrent = x0 - 2*x0 #on déclare une variable a l'opposé de x0
xprec = x0 #on stock la nouvelle valeur de x0

plt.plot(x0,parabole(x0),'ok')


while(abs(xprec - xcurrent) > epsilon): #condition qui va arreter la convergence
    xprec  = xcurrent #on stock xprec comme xpcurrent
    print("xprec" + str(xprec))
    xcurrent = xprec - nu*2*xprec #on défini la nouvelle valeur de xcurrent
    print("xcurrent" + str(xcurrent))
    plt.plot(xcurrent,parabole(xcurrent),'ob') #creer un point
    # plt.pause(1) -> peu utile
    
plt.plot(xcurrent,parabole(xcurrent),'xr')
print(xcurrent)

Matplotlib is building the font cache; this may take a moment.


Using matplotlib backend: TkAgg
xprec-250
xcurrent-200.0
xprec-200.0
xcurrent-160.0
xprec-160.0
xcurrent-128.0
xprec-128.0
xcurrent-102.4
xprec-102.4
xcurrent-81.92
xprec-81.92
xcurrent-65.536
xprec-65.536
xcurrent-52.4288
xprec-52.4288
xcurrent-41.94304
xprec-41.94304
xcurrent-33.554432000000006
xprec-33.554432000000006
xcurrent-26.843545600000006
xprec-26.843545600000006
xcurrent-21.474836480000004
xprec-21.474836480000004
xcurrent-17.179869184000005
xprec-17.179869184000005
xcurrent-13.743895347200004
xprec-13.743895347200004
xcurrent-10.995116277760003
xprec-10.995116277760003
xcurrent-8.796093022208002
xprec-8.796093022208002
xcurrent-7.036874417766401
xprec-7.036874417766401
xcurrent-5.629499534213121
xprec-5.629499534213121
xcurrent-4.503599627370496
xprec-4.503599627370496
xcurrent-3.602879701896397
xprec-3.602879701896397
xcurrent-2.8823037615171176
xprec-2.8823037615171176
xcurrent-2.305843009213694
xprec-2.305843009213694
xcurrent-1.8446744073709553
xprec-1.8446744073709553


2. Retrouvez dans le code les étapes de l’algorithme de descente du gradient en repérant bien l'utilisation de la dérivée.
3. Testez en modifiant l’initialisation de la position du minimum.
4. Comment peut-on obtenir une estimation plus précise de la position du minimum?
5. Testez en modifiant la variable <code>nu</code> par une autre valeur constante inférieure à 1, par exemple <code> nu = 0.6</code>.
Que se passe-t-il si la valeur de nu est fixée à 1 ? Est-ce spécifique à la fonction choisie ?
6. Comparez la version suivante du script avec la précédente

In [6]:
%matplotlib
import matplotlib.pyplot as plt

def parabole(x):
    return x * x

x = np.linspace(-300,300,600)
y = [parabole(i) for i in x]

epsilon = 0.1
attenuation = 3

plt.plot(x,y,'g')

x0=250
xcurrent = x0 - 2*x0
xprec = x0

plt.plot(x0,parabole(x0),'ok')

while(abs(xprec - xcurrent) > epsilon):
    xprec  = xcurrent
    nu = 1/np.log(attenuation)
    print("nu vaut: " +str(nu))
    attenuation = attenuation+1
    xcurrent = xprec - nu*2*xprec
    plt.plot(xcurrent,parabole(xcurrent),'ob')
    plt.pause(1)
plt.plot(xcurrent,parabole(xcurrent),'xr')


Using matplotlib backend: TkAgg
nu vaut: 0.9102392266268375
nu vaut: 0.7213475204444817
nu vaut: 0.6213349345596119
nu vaut: 0.5581106265512472
nu vaut: 0.5138983423697507
nu vaut: 0.48089834696298783


7. Comment évolue la variable <code>nu</code> au fur et à mesure des itérations ? Quel est l'intérêt de procéder ainsi?


### Exercice 3. Descente de gradient pour trouver le minimum d’un polynôme

1. On choisit comme exemple le polynôme $30 − 61x + 41x^2 − 11x^3 + x^4$ . Ecrivez un script python
qui affiche ce polynôme entre 0 et 6 et qui montre les étapes de la descente de gradient à partir de la valeur initiale 5.

In [18]:
import math
%matplotlib
import matplotlib.pyplot as plt
def parabole(x):
    return 30 - 61*x + 41*math.pow(x,2) - 11*math.pow(x,3) + math.pow(x,4)
def script():
    x = np.linspace(-300,300,600)
    y = [parabole(i) for i in x]

    epsilon = 0.1
    attenuation = 3

    plt.plot(x,y,'g')

    x0=5
    xcurrent = x0 - 2*x0
    xprec = x0

    plt.plot(x0,parabole(x0),'ok')

    while(abs(xprec - xcurrent) > epsilon):
        xprec  = xcurrent
        #nu = 1/np.log(attenuation)
        print("nu vaut: " +str(nu))
        attenuation = attenuation+1
        xcurrent = xprec - nu*2*xprec
        plt.plot(xcurrent,parabole(xcurrent),'ob')
        plt.pause(1)
    plt.plot(xcurrent,parabole(xcurrent),'xr')


Using matplotlib backend: TkAgg



2. Changez la valeur initiale à 0.
3. Faites varier les paramètres de la descente de gradient (taux d'apprentissage, test d’arrêt) et commentez le
comportement de l’algorithme.

### Exercice 4. Descente de gradient pour trouver le minimum d’une surface

1. On choisit comme exemple la fonction définie par $f(x,y) = (x−1)(x−2)+(y+3)(y+4)$. On visualise une partie de la surface correspondante avec le code ci-dessous. Quels sont les intervalles de variation de $x$ et $y$ dans ce code? Quelles sont les coordonnées du minimum ?

In [16]:
from mpl_toolkits.mplot3d import Axes3D

def f(x,y):
    return (x - 1) * (x - 2) + (y + 3) * (y + 4)

x = np.linspace(-8, 8, 160) 
y = np.linspace(-8, 8, 160)
x, y = np.meshgrid(x, y)

z = f(x, y)

ax = Axes3D(plt.figure())

ax.plot_surface(x, y, z) 
plt.show()


2. Ecrivez une fonction python <code>animationDescenteSurface(pdep)</code> qui affiche cette surface et qui montre les étapes de la descente de gradient à partir du point initial <code>pdep</code> donné comme vecteur de deux coordonnées. Pour afficher un point 3D vous utiliserez la fonction <code>scatter</code> de <code>Axes3D</code>.

3. Testez avec comme point initial <code>pdep = (1, -5)</code> puis <code>(-1, -3)</code>, <code>(-1, -5)</code> et <code>(2, -4)</code>.

### Exercice 5. Application : régression linéaire

On veut calculer la droite de régression linéaire correspondant à un nuage de
points 2D $\{(x_1, y_1), \cdots , (x_m, y_m)\}$, c'est-à-dire la droite $y = \theta_1x + \theta_0$ qui minimise le critère suivant : 
$$
\frac 1 m \sum \left( \theta_0 + \theta_1 x_i - y_i\right)^2.
$$

Autrement dit, on cherche à minimiser la moyenne des distances verticales entre chaque point du nuage et la droite. <br>
Utilisez une descente de gradient (en 2D) pour trouver les caractéristiques $\theta_0$ et $\theta_1$ de la droite de régression linéaire correspondant à un nuage de points. Pour générer un nuage de point, vous pouvez utiliser le code suivant :

In [17]:
from random import random
m = 40
sizeNoise = 10
x = [random()*50 + 5 for i in range(m)]
noise = [random() * sizeNoise for i in range(m)] # ou np.rand(m,1) * sizeNoise
pente = 0.8
b =  20
y = [b + pente*x[i] + noise[i] for i in range(m)] 

plt.plot(x,y,'bx')

In [28]:
def grad(Teta, x, y):
    i = 0
    j = 0
    s0 = 0
    s1 = 0
    #n est la taille du tableau x 
    n = np.size(x)
    for i in range(n):
        s0 += (Teta[0] + Teta[1])*(x[i] - y[i])
    for j in range(n):
        s1 += x[i]*(Teta[0] + Teta[1])*(x[i] - y[i])
    Teta[0] = (2/n) * s0 
    Teta[1] = (2/n) * s1 
    return Teta


In [ ]:
def regLin(x, y):
    #vecteurs initiaux
    v0 = 20
    Teta = [0,0]
    Vcurrent = v0 - 2*v0
    Vprec = v0
    # parametres de la descente
    nu = 0.9
    epsilon = 0.01
    # loop d'évolution
    while(nu > epsilon):
        Vcurrent = Vprec - nu*grad(f, Vcurrent)